"""initramfs and unified kernel images (mkinitcpio), Secure Boot keys and systemd-boot."""

import logging
from dataclasses import asdict, dataclass

from arch_installer.config.models import (
    CRYPTROOT_MAPPER_NAME,
    InstallerConfig,
    LoaderConfig,
    UkiVariantConfig,
)
from arch_installer.executors.base import (
    SBCTL_DB_KEY,
    SBCTL_PK_KEY,
    TARGET_EFI,
    TARGET_ROOT,
    StepExecutor,
    detect_luks_uuid,
    file_exists,
    partition_uuid,
    stable_disk_path,
    write_file,
)
from arch_installer.executors.gpu import NVIDIA_INITRAMFS_MODULES

logger = logging.getLogger(__name__)

UKI_DIRECTORY = "/efi/EFI/Linux"
# the UKI without extra kernel parameters always exists; its files carry the suffix "default"
PLAIN_VARIANT = UkiVariantConfig(suffix="default", params="")
BOOTLOADER_BINARIES = ("/efi/EFI/BOOT/BOOTX64.EFI", "/efi/EFI/systemd/systemd-bootx64.efi")
# the LUKS header sits on the USB drive, so the initramfs must reach USB storage on any
# machine; "?" lets mkinitcpio skip a module the kernel has built in
USB_STORAGE_INITRAMFS_MODULES = (
    "xhci_pci?",
    "ehci_pci?",
    "ohci_pci?",
    "uhci_hcd?",
    "usb_storage?",
    "uas?",
    "sd_mod?",
)


# the two devices that only unlock root together: the internal disk, named by its
# /dev/disk/by-id link, and the drive's header partition, named by its partition UUID
@dataclass(frozen=True)
class DetachedLuksHeader:
    encrypted_device_path: str
    header_partition_uuid: str


def mkinitcpio_conf(hooks: tuple[str, ...], modules: tuple[str, ...]) -> str:
    return f"""# mkinitcpio configuration
# generated by arch_installer
MODULES=({" ".join(modules)})
BINARIES=()
FILES=()
HOOKS=({" ".join(hooks)})
"""


def uki_path(kernel: str, variant: UkiVariantConfig) -> str:
    return f"{UKI_DIRECTORY}/arch-{kernel}-{variant.suffix}.efi"


def cmdline_file(kernel: str, variant: UkiVariantConfig) -> str:
    return f"/etc/kernel/cmdline-{kernel}-{variant.suffix}"


def kernel_preset(kernel: str, variants: tuple[UkiVariantConfig, ...]) -> str:
    # preset names can't contain dashes, the UKI file names keep them
    preset_names = ["fallback", *(variant.suffix.replace("-", "_") for variant in variants)]
    entries = "".join(
        f"""{variant.suffix.replace("-", "_")}_uki="{uki_path(kernel, variant)}"
{variant.suffix.replace("-", "_")}_options="--splash /usr/share/systemd/bootctl/splash-arch.bmp --cmdline {cmdline_file(kernel, variant)}"
"""
        for variant in variants
    )
    return f"""# mkinitcpio preset file for {kernel} (UKI)
# generated by arch_installer
ALL_config="/etc/mkinitcpio.conf"
ALL_kver="/boot/vmlinuz-{kernel}"
microcode=(/boot/*-ucode.img)

PRESETS=({" ".join(f"'{name}'" for name in preset_names)})

# fallback initramfs for snapshot UKI generation
fallback_image="/boot/initramfs-{kernel}.img"

{entries}"""


def loader_conf(loader: LoaderConfig) -> str:
    return f"""# systemd-boot loader configuration
# generated by arch_installer
timeout {loader.timeout}
console-mode {loader.console_mode}
editor {"yes" if loader.editor else "no"}
"""


def kernel_cmdline(
    config: InstallerConfig,
    luks_uuid: str,
    detached_header: DetachedLuksHeader | None,
    resume_offset: str | None,
) -> str:
    cmdline = config.boot.cmdline
    parts = [
        f"rd.luks.name={luks_uuid}={CRYPTROOT_MAPPER_NAME}",
        f"root={config.storage.cryptroot_device}",
        "rw" if cmdline.rw else "ro",
        f"rootfstype={cmdline.rootfstype}",
        f"rootflags={cmdline.rootflags}",
    ]
    if detached_header:
        # the LUKS UUID lives only in the header, so the data device is named explicitly
        parts.append(f"rd.luks.data={luks_uuid}={detached_header.encrypted_device_path}")
        parts.append(
            f"rd.luks.options={luks_uuid}="
            f"header=/dev/disk/by-partuuid/{detached_header.header_partition_uuid}"
        )
    if cmdline.quiet:
        parts.append("quiet")
    for parameter, value in asdict(cmdline.hardening).items():
        # an empty string or 0 leaves the kernel default in place
        if value not in ("", 0):
            parts.append(f"{parameter}={value}")
    swap = config.storage.swap
    if swap.enabled and swap.hibernation:
        # the swapfile lives on the encrypted btrfs, so resume goes through the mapper
        parts.append(f"resume={config.storage.cryptroot_device}")
        if resume_offset:
            parts.append(f"resume_offset={resume_offset}")
    return " ".join(parts)


def uki_variants(config: InstallerConfig) -> tuple[UkiVariantConfig, ...]:
    # each configured variant other than the plain one adds a UKI per kernel
    extra = tuple(
        variant for variant in config.boot.variants if variant.suffix != PLAIN_VARIANT.suffix
    )
    return (PLAIN_VARIANT, *extra)


class KernelImagesStepExecutor(StepExecutor):
    def execute(self) -> None:
        hooks = self._config.boot.hooks
        modules = (
            *(NVIDIA_INITRAMFS_MODULES if self._config.gpu.uses_proprietary_nvidia_driver else ()),
            *(USB_STORAGE_INITRAMFS_MODULES if self._config.usb_boot.enabled else ()),
        )
        write_file(
            self._runner, f"{TARGET_ROOT}/etc/mkinitcpio.conf", mkinitcpio_conf(hooks, modules)
        )
        self._runner.run(f"mkdir -p {TARGET_ROOT}{UKI_DIRECTORY}")

        luks_uuid = detect_luks_uuid(self._runner, self._config.luks_header_device)
        if not luks_uuid:
            raise RuntimeError(f"No LUKS header on {self._config.luks_header_device}")

        kernels = [
            kernel
            for kernel in self._config.boot.kernel_packages
            if file_exists(self._runner, f"{TARGET_ROOT}/boot/vmlinuz-{kernel}")
        ]
        if not kernels:
            raise RuntimeError(
                f"None of the kernels {self._config.boot.kernel_packages} is installed"
            )

        variants = uki_variants(self._config)
        logger.info(
            "Kernels: %s, UKI variants: %s",
            ", ".join(kernels),
            ", ".join(variant.suffix for variant in variants),
        )
        cmdline = kernel_cmdline(
            self._config, luks_uuid, self._detached_header(), self._swapfile_resume_offset()
        )

        self._runner.run(f"mkdir -p {TARGET_ROOT}/etc/kernel")
        for kernel in kernels:
            for variant in variants:
                full_cmdline = f"{cmdline} {variant.params}".strip()
                write_file(
                    self._runner,
                    f"{TARGET_ROOT}{cmdline_file(kernel, variant)}",
                    f"{full_cmdline}\n",
                )
            write_file(
                self._runner,
                f"{TARGET_ROOT}/etc/mkinitcpio.d/{kernel}.preset",
                kernel_preset(kernel, variants),
            )
        # manage-snapshot-ukis builds the snapshot cmdlines from this one
        write_file(self._runner, f"{TARGET_ROOT}/etc/kernel/cmdline", f"{cmdline}\n")
        logger.info("Kernel cmdline: %s", cmdline)

        self._prepare_secure_boot()
        logger.info("Generating UKIs...")
        self._runner.run_as_chroot("mkinitcpio -P")
        self._sign_ukis(kernels, variants)

    def _detached_header(self) -> DetachedLuksHeader | None:
        if not self._config.usb_boot.enabled:
            return None
        encrypted_device_path = stable_disk_path(self._runner, self._config.encrypted_device)
        if not encrypted_device_path:
            raise RuntimeError(f"{self._config.encrypted_device} has no /dev/disk/by-id name")
        return DetachedLuksHeader(
            encrypted_device_path=encrypted_device_path,
            header_partition_uuid=partition_uuid(
                self._runner, self._config.usb_boot.luks_header_partition
            ),
        )

    def _swapfile_resume_offset(self) -> str | None:
        swap = self._config.storage.swap
        if not (swap.enabled and swap.hibernation):
            return None
        swap_path = f"{TARGET_ROOT}{swap.path}"
        offset = self._runner.run(
            f"btrfs inspect-internal map-swapfile -r {swap_path}", raise_on_nonzero_exit=False
        ).stdout.strip()
        if offset:
            return offset

        # filefrag fallback, its first extent line looks like
        # "   0:        0..   16383:     192512..    208895:  16384:"
        filefrag = self._runner.run(f"filefrag -v {swap_path}", raise_on_nonzero_exit=False)
        for line in filefrag.stdout.split("\n"):
            parts = line.split()
            if ".." in line and not line.strip().startswith("ext:") and len(parts) >= 4:
                physical_offset = parts[3].replace(".", "").replace(":", "")
                if physical_offset.isdigit():
                    return physical_offset

        logger.warning("Could not determine the swapfile offset, hibernation will not resume")
        return None

    def _prepare_secure_boot(self) -> None:
        setup_mode = self._is_in_setup_mode()
        if not setup_mode:
            logger.info("Secure Boot is not in Setup Mode: UKIs get signed, keys are not enrolled.")

        if file_exists(self._runner, f"{TARGET_ROOT}{SBCTL_PK_KEY}"):
            logger.info("Secure boot keys already exist.")
        elif not self._runner.run_as_chroot(
            "sbctl create-keys", raise_on_nonzero_exit=False
        ).success:
            logger.warning("Could not create Secure Boot keys.")

        secure_boot = self._config.boot.secure_boot
        if setup_mode and secure_boot.enroll_keys:
            self._enroll_keys(secure_boot.include_microsoft_keys)

    def _is_in_setup_mode(self) -> bool:
        # sbctl marks an enabled setup mode with ✗ (insecure state) and a disabled one
        # with ✓, so the words "enabled"/"disabled" on that line are what count
        status = self._runner.run_as_chroot("sbctl status", raise_on_nonzero_exit=False)
        for line in status.stdout.split("\n"):
            if "setup mode" in line.lower():
                return "enabled" in line.lower()

        # sbctl gave no answer, read the SetupMode efivar (last byte) directly
        efivar = self._runner.run_as_chroot(
            "cat /sys/firmware/efi/efivars/SetupMode-* 2>/dev/null | xxd -p | tail -c 3",
            raise_on_nonzero_exit=False,
        )
        return efivar.success and efivar.stdout.strip() == "01"

    def _enroll_keys(self, include_microsoft: bool) -> None:
        enroll_command = (
            "sbctl enroll-keys --microsoft" if include_microsoft else "sbctl enroll-keys"
        )
        logger.info("Enrolling Secure Boot keys (%s)...", enroll_command)
        result = self._runner.run_as_chroot(enroll_command, raise_on_nonzero_exit=False)
        if not result.success:
            logger.warning(
                "Key enrollment failed: %s. Clear the firmware's Secure Boot keys (Setup Mode), "
                "then run: %s",
                result.stderr.strip(),
                enroll_command,
            )

    def _sign_ukis(self, kernels: list[str], variants: tuple[UkiVariantConfig, ...]) -> None:
        if not file_exists(self._runner, f"{TARGET_ROOT}{SBCTL_DB_KEY}"):
            logger.info("Skipping UKI signing (no Secure Boot keys available).")
            return
        for kernel in kernels:
            for variant in variants:
                path = uki_path(kernel, variant)
                if file_exists(self._runner, f"{TARGET_ROOT}{path}"):
                    # -s records the file in sbctl's database, so its hooks re-sign rebuilt UKIs
                    self._runner.run_as_chroot(f"sbctl sign -s {path}", raise_on_nonzero_exit=False)


class BootloaderStepExecutor(StepExecutor):
    def execute(self) -> None:
        if self._config.usb_boot.enabled:
            self._install_on_usb_boot_drive()
        else:
            self._runner.run_as_chroot("bootctl install --esp-path=/efi")
        write_file(
            self._runner, f"{TARGET_EFI}/loader/loader.conf", loader_conf(self._config.boot.loader)
        )

        for path in BOOTLOADER_BINARIES:
            if file_exists(self._runner, f"{TARGET_ROOT}{path}"):
                self._runner.run_as_chroot(f"sbctl sign -s {path}", raise_on_nonzero_exit=False)

    def _install_on_usb_boot_drive(self) -> None:
        # the firmware starts the drive through its removable-media path
        # (EFI/BOOT/BOOTX64.EFI), so the machine's NVRAM keeps no boot entry and no
        # system token pointing at it. a random seed would tie the portable drive to
        # this machine's token, and its refresh service would write that token
        self._runner.run_as_chroot(
            "bootctl install --esp-path=/efi --variables=no --random-seed=no"
        )
        self._runner.run_as_chroot("systemctl mask systemd-boot-random-seed.service")
