"""pacman mirrors declared in system.mirrors.

the live ISO's mirrorlist is replaced before pacstrap runs; pacstrap then copies it
into the installed system, so both use the declared mirrors.
"""

import logging

from arch_installer.executors.base import Executor, write_file

logger = logging.getLogger(__name__)

LIVE_MIRRORLIST = "/etc/pacman.d/mirrorlist"


def mirrorlist(mirrors: tuple[str, ...]) -> str:
    lines = ["# generated by arch_installer from system.mirrors"]
    lines.extend(f"Server = {mirror}" for mirror in mirrors)
    return "\n".join(lines) + "\n"


class PacmanMirrorsStepExecutor(Executor):
    def execute(self) -> None:
        mirrors = self._config.system.mirrors
        if mirrors.use_reflector:
            countries = ",".join(mirrors.reflector_countries)
            logger.info("Ranking mirrors with reflector (%s)...", countries)
            self._runner.run(
                f"reflector --country '{countries}' --protocol https --latest 20 "
                f"--sort rate --save {LIVE_MIRRORLIST}"
            )
        else:
            logger.info("Using the %s mirrors from config.yaml", len(mirrors.mirrors))
            write_file(self._runner, LIVE_MIRRORLIST, mirrorlist(mirrors.mirrors))
