"""Snapper configuration, bootable snapshot UKIs and snapshot notifications."""

import logging

from arch_installer.config.models import SnapperVolumeConfig
from arch_installer.executors.base import (
    TARGET_ROOT,
    StepExecutor,
    directory_exists,
    file_exists,
    is_mountpoint,
    write_file,
)

logger = logging.getLogger(__name__)

SNAPSHOT_MANAGER = "/usr/local/bin/manage-snapshot-ukis"
SNAPSHOT_MANAGER_SETTINGS = "/etc/default/manage-snapshot-ukis"
SNAPSHOT_REFRESH_HOOK_SCRIPT = "/usr/local/bin/refresh-snapshot-ukis"
MICROCODE_PACKAGES = ("amd-ucode", "intel-ucode")


def yes_no(enabled: bool) -> str:
    return "yes" if enabled else "no"


def snapper_volume_config(volume: SnapperVolumeConfig, allow_groups: tuple[str, ...]) -> str:
    retention = volume.retention
    return f"""# snapper config for {volume.subvolume}
# created by arch_installer (D-Bus not available in chroot)

SUBVOLUME="{volume.subvolume}"
FSTYPE="btrfs"
ALLOW_USERS=""
ALLOW_GROUPS="{",".join(allow_groups)}"
SYNC_ACL="yes"
BACKGROUND_COMPARISON="yes"

NUMBER_CLEANUP="{yes_no(volume.cleanup)}"
NUMBER_MIN_AGE="1800"
NUMBER_LIMIT="{volume.number_limit}"
NUMBER_LIMIT_IMPORTANT="{volume.number_limit_important}"

TIMELINE_CREATE="{yes_no(volume.timeline)}"
TIMELINE_CLEANUP="{yes_no(volume.cleanup)}"
TIMELINE_MIN_AGE="1800"
TIMELINE_LIMIT_HOURLY="{retention.hourly}"
TIMELINE_LIMIT_DAILY="{retention.daily}"
TIMELINE_LIMIT_WEEKLY="{retention.weekly}"
TIMELINE_LIMIT_MONTHLY="{retention.monthly}"
TIMELINE_LIMIT_YEARLY="{retention.yearly}"

EMPTY_PRE_POST_CLEANUP="{yes_no(volume.cleanup)}"
EMPTY_PRE_POST_MIN_AGE="1800"
"""


SNAP_PAC_ROOT_CONFIG = """[root]
snapshot = yes
cleanup = timeline
"""


def snapshot_manager_settings(snapshot_count: int, preferred_kernel: str) -> str:
    return f"""# read by manage-snapshot-ukis, generated by arch_installer from config.yaml
SNAPSHOT_COUNT={snapshot_count}
PREFERRED_KERNEL={preferred_kernel}
"""


SNAPSHOT_BOOT_ENTRIES_SERVICE = f"""[Unit]
Description=Refresh systemd-boot entries for BTRFS snapshots
After=snapper-cleanup.service snapper-timeline.service

[Service]
Type=oneshot
ExecStart={SNAPSHOT_MANAGER} refresh-settled
"""


SNAPSHOT_BOOT_ENTRIES_PATH = """[Unit]
Description=Watch for snapper snapshot changes

[Path]
PathChanged=/.snapshots
Unit=snapper-boot-entries.service

[Install]
WantedBy=multi-user.target
"""


def snapshot_refresh_pacman_hook(kernel_packages: tuple[str, ...]) -> str:
    package_targets = "\n".join(
        f"Target = {package}" for package in (*kernel_packages, *MICROCODE_PACKAGES)
    )
    return f"""# refreshes bootable snapshot UKIs once a kernel or initramfs changed
# runs after 90-mkinitcpio-install.hook, which rebuilds the system UKIs

[Trigger]
Type = Path
Operation = Install
Operation = Upgrade
Target = usr/lib/modules/*/vmlinuz
Target = usr/lib/initcpio/*

[Trigger]
Type = Package
Operation = Install
Operation = Upgrade
{package_targets}

[Action]
Description = Refreshing snapshot boot UKIs...
When = PostTransaction
Exec = {SNAPSHOT_REFRESH_HOOK_SCRIPT}
NeedsTargets
"""


SNAPSHOT_REFRESH_HOOK_SCRIPT_CONTENT = f"""#!/usr/bin/env bash
# called by the pacman hook after kernel updates; never fails the transaction
set -uo pipefail

LOG_FILE="/var/log/snapshot-uki-refresh.log"

log() {{
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" | tee -a "$LOG_FILE"
}}

if [ ! -x "{SNAPSHOT_MANAGER}" ]; then
    log "Warning: {SNAPSHOT_MANAGER} not found, skipping refresh"
    exit 0
fi

if [ ! -d "/.snapshots" ] || [ -z "$(ls -A /.snapshots 2>/dev/null)" ]; then
    log "No snapshots found in /.snapshots, skipping UKI refresh"
    exit 0
fi

log "Refreshing snapshot UKIs after kernel update..."
if "{SNAPSHOT_MANAGER}" refresh >> "$LOG_FILE" 2>&1; then
    log "Snapshot UKIs refreshed successfully"
else
    log "Warning: Failed to refresh some snapshot UKIs"
fi
exit 0
"""


SNAPPER_NOTIFY_SERVICE = """[Unit]
Description=Notify on snapper snapshot creation
After=snapper-timeline.timer snap-pac.service

[Service]
Type=oneshot
ExecStart=/usr/local/bin/snapper-notify
"""


SNAPPER_NOTIFY_PATH = """[Unit]
Description=Watch for new snapshots and notify

[Path]
PathChanged=/.snapshots
Unit=snapper-notify.service

[Install]
WantedBy=multi-user.target
"""


SNAPPER_NOTIFY_SCRIPT = """#!/bin/bash
# Desktop notification for snapper snapshot creation
# Requires: libnotify (notify-send)

set -euo pipefail

SNAPSHOT_DIR="/.snapshots"
LAST_NOTIFIED_FILE="/tmp/snapper-last-notified"

latest_snapshot=$(ls -1t "$SNAPSHOT_DIR" 2>/dev/null | head -n1)
[[ -z "$latest_snapshot" ]] && exit 0

# avoid duplicate notifications
if [[ -f "$LAST_NOTIFIED_FILE" ]]; then
    last_notified=$(cat "$LAST_NOTIFIED_FILE")
    [[ "$latest_snapshot" == "$last_notified" ]] && exit 0
fi

# get snapshot info
info_file="$SNAPSHOT_DIR/$latest_snapshot/info.xml"
if [[ -f "$info_file" ]]; then
    description=$(grep -oP '(?<=<description>).*(?=</description>)' "$info_file" 2>/dev/null || echo "")
    snap_type=$(grep -oP '(?<=<type>).*(?=</type>)' "$info_file" 2>/dev/null || echo "single")
else
    description=""
    snap_type="single"
fi

# send notification to logged-in user
for uid in $(loginctl list-users --no-legend | awk '{print $1}'); do
    user=$(id -nu "$uid" 2>/dev/null || continue)
    export DISPLAY=":0"
    export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$uid/bus"

    title="Snapshot #$latest_snapshot created"
    body="${description:-$snap_type snapshot}"

    sudo -u "$user" notify-send -i drive-harddisk -a "Snapper" "$title" "$body" 2>/dev/null || true
done

echo "$latest_snapshot" > "$LAST_NOTIFIED_FILE"
"""


class SnapperStepExecutor(StepExecutor):
    def execute(self) -> None:
        snapper = self._config.snapper
        logger.info("Configuring snapper (allowed groups: %s)...", ", ".join(snapper.allow_groups))

        if not self._runner.run_as_chroot("pacman -Q snapper", raise_on_nonzero_exit=False).success:
            self._runner.run_as_chroot("pacman -S --noconfirm snapper snap-pac")
        self._runner.run(f"mkdir -p {TARGET_ROOT}/etc/snapper/configs")
        self._runner.run(f"mkdir -p {TARGET_ROOT}/etc/conf.d")

        for name, volume in snapper.volumes.items():
            config_file = f"{TARGET_ROOT}/etc/snapper/configs/{name}"
            if file_exists(self._runner, config_file):
                logger.info("Snapper config '%s' already exists, updating it.", name)
            else:
                self._prepare_snapshots_subvolume(volume)
            write_file(
                self._runner, config_file, snapper_volume_config(volume, snapper.allow_groups)
            )

        configured_names = " ".join(snapper.volumes)
        write_file(
            self._runner,
            f"{TARGET_ROOT}/etc/conf.d/snapper",
            f'SNAPPER_CONFIGS="{configured_names}"\n',
        )
        self._runner.run_as_chroot("systemctl enable snapper-timeline.timer")
        self._runner.run_as_chroot("systemctl enable snapper-cleanup.timer")

        if snapper.snap_pac:
            self._runner.run(f"mkdir -p {TARGET_ROOT}/etc/snap-pac.d")
            write_file(
                self._runner, f"{TARGET_ROOT}/etc/snap-pac.d/root.conf", SNAP_PAC_ROOT_CONFIG
            )

    def _prepare_snapshots_subvolume(self, volume: SnapperVolumeConfig) -> None:
        # snapper expects <subvolume>/.snapshots; mount the dedicated subvolume there
        # instead of the nested one `snapper create-config` would make
        snapshots_directory = f"{TARGET_ROOT}{volume.snapshots_path}"
        if is_mountpoint(self._runner, snapshots_directory):
            self._runner.run(f"umount {snapshots_directory}")
        if directory_exists(self._runner, snapshots_directory):
            if self._runner.run(
                f"btrfs subvolume show {snapshots_directory}", raise_on_nonzero_exit=False
            ).success:
                self._runner.run(
                    f"btrfs subvolume delete {snapshots_directory}", raise_on_nonzero_exit=False
                )
            else:
                self._runner.run(f"rmdir {snapshots_directory}", raise_on_nonzero_exit=False)

        self._runner.run(f"mkdir -p {snapshots_directory}")
        mount_options = self._config.storage.btrfs.mount_options
        self._runner.run(
            f"mount -t btrfs -o subvol={volume.snapshots_subvolume},{mount_options} "
            f"{self._config.storage.cryptroot_device} {snapshots_directory}"
        )
        self._runner.run(f"chmod 750 {snapshots_directory}")


class BootableSnapshotsStepExecutor(StepExecutor):
    def execute(self) -> None:
        boot = self._config.boot
        snapshot_count = self._config.snapper.bootable_snapshot_count
        logger.info("Enabling bootable snapshots (newest %s get a UKI)...", snapshot_count)

        write_file(
            self._runner,
            f"{TARGET_ROOT}{SNAPSHOT_MANAGER_SETTINGS}",
            snapshot_manager_settings(snapshot_count, boot.kernel_packages[0]),
        )

        self._runner.run(f"mkdir -p {TARGET_ROOT}/etc/pacman.d/hooks {TARGET_ROOT}/usr/local/bin")
        write_file(
            self._runner,
            f"{TARGET_ROOT}/etc/pacman.d/hooks/95-snapshot-uki-refresh.hook",
            snapshot_refresh_pacman_hook(boot.kernel_packages),
        )
        hook_script = f"{TARGET_ROOT}{SNAPSHOT_REFRESH_HOOK_SCRIPT}"
        write_file(self._runner, hook_script, SNAPSHOT_REFRESH_HOOK_SCRIPT_CONTENT)
        self._runner.run(f"chmod +x {hook_script}")

        write_file(
            self._runner,
            f"{TARGET_ROOT}/etc/systemd/system/snapper-boot-entries.service",
            SNAPSHOT_BOOT_ENTRIES_SERVICE,
        )
        write_file(
            self._runner,
            f"{TARGET_ROOT}/etc/systemd/system/snapper-boot-entries.path",
            SNAPSHOT_BOOT_ENTRIES_PATH,
        )
        self._runner.run_as_chroot("systemctl enable snapper-boot-entries.path")


class SnapshotNotificationsStepExecutor(StepExecutor):
    def execute(self) -> None:
        logger.info("Enabling desktop notifications for new snapshots...")
        notify_script = f"{TARGET_ROOT}/usr/local/bin/snapper-notify"
        self._runner.run(f"mkdir -p {TARGET_ROOT}/usr/local/bin")
        write_file(self._runner, notify_script, SNAPPER_NOTIFY_SCRIPT)
        self._runner.run(f"chmod +x {notify_script}")
        write_file(
            self._runner,
            f"{TARGET_ROOT}/etc/systemd/system/snapper-notify.service",
            SNAPPER_NOTIFY_SERVICE,
        )
        write_file(
            self._runner,
            f"{TARGET_ROOT}/etc/systemd/system/snapper-notify.path",
            SNAPPER_NOTIFY_PATH,
        )
        self._runner.run_as_chroot("systemctl enable snapper-notify.path")
