"""Boot-related configuration templates."""


def mkinitcpio_conf(hooks: str) -> str:
    return f"""# Generated by arch_installer
MODULES=()
BINARIES=()
FILES=()
HOOKS=({hooks})
"""


def mkinitcpio_preset(
    kernel: str,
    kver: str,
    presets_str: str,
    base_content: str,
    variants_content: str,
) -> str:
    return f"""# mkinitcpio preset file for {kernel} (UKI)
# Generated by arch_installer
ALL_config="/etc/mkinitcpio.conf"
ALL_kver="{kver}"
microcode=(/boot/*-ucode.img)

PRESETS=({presets_str})

# Fallback initramfs for snapshot UKI generation
fallback_image="/boot/initramfs-{kernel}.img"

{variants_content}"""


def mkinitcpio_preset_variant(preset_name: str, uki_path: str, cmdline_file: str) -> str:
    return f"""{preset_name}_uki="{uki_path}"
{preset_name}_options="--splash /usr/share/systemd/bootctl/splash-arch.bmp --cmdline {cmdline_file}"
"""


def systemd_boot_loader_conf(timeout: int, console_mode: str, editor_enabled: bool) -> str:
    editor_val = "yes" if editor_enabled else "no"
    return f"""timeout {timeout}
console-mode {console_mode}
editor {editor_val}
"""


MKINITCPIO_CONF = mkinitcpio_conf
MKINITCPIO_PRESET = mkinitcpio_preset
SYSTEMD_BOOT_LOADER_CONF = systemd_boot_loader_conf
