"""Templates for mkinitcpio configuration and presets."""


def mkinitcpio_main_conf(hooks: str) -> str:
    """Generate the main /etc/mkinitcpio.conf content."""
    return f"""# mkinitcpio configuration
# generated by arch_installer
MODULES=()
BINARIES=()
FILES=()
HOOKS=({hooks})
"""


def mkinitcpio_kernel_preset_header(
    kernel: str,
    kver_path: str,
    presets_list: str,
) -> str:
    """Generate the header section of a kernel preset file."""
    return f"""# mkinitcpio preset file for {kernel} (UKI)
# generated by arch_installer
ALL_config="/etc/mkinitcpio.conf"
ALL_kver="{kver_path}"
microcode=(/boot/*-ucode.img)

PRESETS=({presets_list})

# fallback initramfs for snapshot UKI generation
fallback_image="/boot/initramfs-{kernel}.img"

"""


def mkinitcpio_uki_variant_entry(
    preset_name: str,
    uki_path: str,
    cmdline_file: str,
) -> str:
    """Generate a single UKI variant entry for a preset file."""
    return f"""{preset_name}_uki="{uki_path}"
{preset_name}_options="--splash /usr/share/systemd/bootctl/splash-arch.bmp --cmdline {cmdline_file}"
"""
