"""Templates for systemd-boot configuration."""


def systemd_boot_loader_conf(
    timeout: int,
    console_mode: str,
    editor_enabled: bool,
) -> str:
    """Generate /efi/loader/loader.conf content."""
    editor_val = "yes" if editor_enabled else "no"
    return f"""# systemd-boot loader configuration
# generated by arch_installer
timeout {timeout}
console-mode {console_mode}
editor {editor_val}
"""


def systemd_boot_entry(
    title: str,
    efi_path: str,
) -> str:
    """Generate a boot entry for systemd-boot."""
    return f"""title   {title}
efi     {efi_path}
"""
